# Use the official PostgreSQL image as the base image
FROM postgres:latest

# Set the environment variables
ENV POSTGRES_USER root
ENV POSTGRES_PASSWORD root

# Expose the default PostgreSQL port
EXPOSE 5432

# Start the PostgreSQL server
CMD ["postgres"]
